### PR TITLE
fix adminer

### PR DESCRIPTION
**Pull request by OnGle**
(fixes adminer, missed in earlier 17.0 update)

### CODE REVIEW

**Review by Christie018 — APPROVED** [review]
The code changes of this PR to add to appliance v17.0 update include refactoring done to adminer lgtm. I would only say to ensure update changes made for adminer are documented in changelog.

**Comment by JedMeister** [comment]
LGTM although as Mattie noted, perhaps give the changelog a quick tweak... :smile:

**Comment by OnGle** [comment]
Was mayan-edms released with broken adminer? Afaik this was only broken in dev (and I missed in my first PR)

**Comment by JedMeister** [comment]
Ah yes, good point @OnGle - the version with broken adminer wasn't released. So although fixing adminer was a change made in v17.x, as it was never released and was working fine in v16.x then it's not unreasonable to not explicitly note it in the changelog. As you already included an updated changelog (see https://github.com/turnkeylinux-apps/mayan-edms/pull/5/files) I think this is good to go...

**Pull request merged**
